### PR TITLE
fix assets preload for primary fragments on aws s3 (#228)

### PR DESCRIPTION
**Pull request by guilhermecvm**
Adding support to aws custom headers when preloading assets.

### CODE REVIEW

**Comment by shuhei** [comment]
👍

**Comment by DeTeam** [comment]
:+1:

**Comment by DeTeam** [comment]
@vigneshshanmugam have a look, too?

**Comment by vigneshshanmugam** [comment]
@guilhermecvm Thanks for the PR, can you add a test in this section https://github.com/zalando/tailor/blob/master/tests/tailor.js#L367?

**Comment by vigneshshanmugam** [comment]
👍

**Comment by DeTeam** [comment]
:+1:

**Pull request merged**
