### PR TITLE
Fixing markup formatting issues.

### PR DESCRIPTION
**Pull request by diemol**
Just edited file to fix markup formatting issues.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
👍

**Comment by vigneshshanmugam** [comment]
Thanks @diemol

**Comment by diemol** [comment]
Is there something wrong with the PR? Can I help in some way to get it merged?

**Comment by diemol** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
