### PR TITLE
Use the node v8 promisify API to remove unnecessary code

### LINKED ISSUE #153: Use the node v8 promisify API to remove unnecessary code
We can remove some unnecessary explicit `promisify` code by using the v8 `utils.promisify` API (https://nodejs.org/en/blog/release/v8.0.0/#improved-support-for-promises). 

E.g.: This [function](https://github.com/zalando/tailor/blob/master/lib/fetch-template.js#L29) can be changed to a much elegant and declarative implementation.

```javascript
const readFile = (path) => 
    new Promise((resolve, reject) => {
        fs.readFile(path, 'utf-8', (err, data) => {
            if (err) {
                reject(new TemplateError(err));
                return;
            } 
            resolve(data);
        });
    });
```
to

```javascript
const util = require('util');

const readFile = (path) => 
    util.promisify(fs.readFile)(path)
        .catch(err => new TemplateError(err));
```

### PR DESCRIPTION
**Pull request by addityasingh**
- closes #153 
- Use the node 8 `promisify` API to remove unnecessary code
- Polyfill it for older node versions

### CODE REVIEW

**Comment by addityasingh** [comment]
This is auto-generated by `npm 5` to optimise the install time

**Comment by vigneshshanmugam** [comment]
I am aware of that, But we already use `yarn.lock` for determinism.

**Comment by addityasingh** [comment]
Closing this for now, since there are some possible performance issue with the `util.promisify` library

**Comment by addityasingh** [comment]
Seems like wrong PR to me. I will close this and create a new 1

**Comment by vigneshshanmugam** [comment]
The title seems wrong here.  But we need tests for fetch-templates as well :)

**Pull request closed without merging**
