### PR TITLE
Update Buffer to use Node v8 syntax

### LINKED ISSUE #149: fix deprecation warnings in Node 8
Node 8 provides deprecation warnings when running with --pending-deprecation flag and we need small fixes in tailor core. 

 + [ ] Move from Buffer() to Buffer.allocUnsafe (https://nodejs.org/en/blog/release/v8.0.0/#buffer-changes)
 + [ ] Include Node 8 as part of travis build

### PR DESCRIPTION
**Pull request by addityasingh**
- closes #149 
- Update Buffer to use Node v8 syntax

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Can you run the benchmark with Buffer.from and Buffer.allocUnsafe?

**Comment by addityasingh** [comment]
The benchmark tests are failing for me with a `TCP socket timeout` error

**Comment by vigneshshanmugam** [comment]
Hmm, works for me though

## With buffer.from 
```
Tailor Overhead Metrics {
  "min": 0.17091100000004644,
  "max": 26.52051499999999,
  "median": 0.3406260000000003,
  "p75": 0.4464815000000044,
  "p95": 0.9002163000000108,
  "p99": 1.840807620000034,
  "p999": 18.234515409000025
}
```

**Comment by addityasingh** [comment]
looks like `Buffer.alloc()` numbers look better than `allocUnsafe()` and `fill()` upto p99. 👍

**Comment by addityasingh** [comment]
@vigneshshanmugam Can you check and confirm if the examples with `parse-template` are working for you after this change? 
```
node examples/fragment-performance
node examples/multiple-fragments-with-custom-amd
```
The above 2 seems to be broken with error:
> TypeError: this.html.charCodeAt is not a function
    at Preprocessor.advance (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/tokenizer/preprocessor.js:124:24)
    at Tokenizer._consume (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/tokenizer/index.js:278:30)
    at Tokenizer.getNextToken (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/tokenizer/index.js:236:23)
    at Parser._runParsingLoop (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/parser/index.js:393:36)
    at Parser.parse (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/parser/index.js:322:10)
    at Object.parse (/Users/adisingh/Documents/dev/projects/node/tailor/node_modules/parse5/lib/index.js:11:19)
    at Transform.applyTransforms (/Users/adisingh/Documents/dev/projects/node/tailor/lib/transform.js:27:34)
    at Promise.resolve.then.transform (/Users/adisingh/Documents/dev/projects/node/tailor/lib/parse-template.js:14:43)

**Comment by vigneshshanmugam** [comment]
Weird. It works properly for me and the tests are passing on all versions. 

Can you give the node version?

**Comment by addityasingh** [comment]
`node v7.8.0`

**Pull request merged**
