### PR TITLE
chore: accept approval from collaborators

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ Accept approvals from zalando org and collaborators.

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
👍

**Comment by vigneshshanmugam** [comment]
@ruiaraujo Does this pass the compliance check?

**Comment by vigneshshanmugam** [comment]
👍

**Comment by boopathi** [comment]
👍

**Comment by addityasingh** [comment]
👍

**Comment by ruiaraujo** [comment]
:+1:

**Pull request merged**
