### PR TITLE
Update Tailor using ES6 features

### PR DESCRIPTION
**Pull request by addi90**
- Use ES6 destructuring wherever applicable
- Use multiline string templates using \` `
- Use `() => {}` and remove verbose code, wherever applicable
- Use Array methods like `.includes()`, wherever applicable
- Add lodash/fp to demo *FP* in `filter-headers.js`

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@addi90 what happened? sending a new PR?

**Comment by addi90** [comment]
@vigneshshanmugam The de-structuring doesn't seem to be working on node-4.x even with the `--harmony` flag. I just installed node 4 locally and trying to make it work. Will create a new PR once done.

**Comment by vigneshshanmugam** [comment]
Well desstructuring isn't supported in node 4.4 versions.

**Comment by addi90** [comment]
Yeah. Now I am checking for using `babel-register`, and possibly `babel-preset-env` for this.

**Comment by vigneshshanmugam** [comment]
I am just thinking whether to drop support for node 4 versions with the next 2.0 release of tailor.. Let me give you an update by tomorrow.

**Comment by addi90** [comment]
Sure. In the meanwhile I will check if its possible to support with minor changes only

**Pull request closed without merging**
