### PR TITLE
Update span names to follow Opentracing conventions

### PR DESCRIPTION
**Pull request by mdodevska**
Updated span name to follow the conventions:
https://github.bus.zalan.do/SRE/opentracing/blob/master/wg-semantic-conventions/best-practices.md

### CODE REVIEW

**Comment by DeTeam** [comment]
:+1:

**Comment by aryszka** [comment]
@DeTeam any idea why the build started failing with this PR?

**Comment by DeTeam** [comment]
@aryszka AFAIK it only works when @vigneshshanmugam opens up a PR :) credentials or smth

**Comment by aryszka** [comment]
@vigneshshanmugam if this is the case, could you please reopen this PR?

**Comment by vigneshshanmugam** [comment]
Ignore that test, its because of sauce labs. 

Thanks @mdodevska 👍

**Pull request merged**
