### PR TITLE
Include demo SPA repos in README

### PR DESCRIPTION
**Pull request by tsnolan23**
The examples provided by default through Tailor are great to get started, but I think linking directly to the SPA examples in the README would be helpful to those looking to dive a bit deeper into more complex and practical usage of Tailor (similar to the techniques used by Zalando in production).

The second of the two example SPAs was built in response to a dependency handling issue (#196)

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Thanks @tsnolan23 for the PR :)

**Comment by vigneshshanmugam** [comment]
👍

**Comment by DeTeam** [comment]
:+1:

**Comment by stevoPerisic** [comment]
@tsnolan23, @vigneshshanmugam how would one put together a SPA with the use of fragments? This is not very clear as SPAs navigate via routes and the HTML is rendered on the front-end not on the server. I hope you see my dilemma, if I change routes within a SPA and want to navigate to another fragment how would I execute that?

**Comment by tsnolan23** [comment]
@vigneshshanmugam I know this has been closed, but @stevoPerisic makes a fair point. I'm also curious on that topic.

In certain instances, you're essentially "forfeiting" the true SPA behavior in terms of routing, no? If the fragment uses say, `react-router` to navigate within itself, it works fine, but in a case where the page is completely changing, it's an entirely new HTTP request through skipper/tailor, to get the new template correct? 

It's not like code splitting where it would just make an asynchronous call for the next fragment?

**Pull request merged**
