### PR TITLE
Support gzip in tailor

### PR DESCRIPTION
**Pull request by ytanruengsri**
Support gzip in tailor

### CODE REVIEW

**Comment by lmineiro** [comment]
seems to awfully simple that it makes me wonder :)

**Comment by ytanruengsri** [comment]
@lmineiro need a support to test this PR

**Comment by grassator** [comment]
@ytanruengsri One of the things missing here is that Tailor should actually send "Accept-Encoding" to fragments.

You can do a couple of things here. For the automated test you can look into how the fragments are tested (we emulate streams from what I remember), so you can just create your own stream and pipe it through gzip and then test the output.

Another thing is to try to start tailor locally and point one of the fragments to any website that uses gzip or, better, start another node.js service that will do that.

**Comment by ytanruengsri** [comment]
see https://github.com/zalando/tailor/pull/76

**Pull request closed without merging**
