### PR TITLE
fix: allow slot named default

### PR DESCRIPTION
**Pull request by cschockaert**
a slot named default will duplicate the content, the PR fix it #295

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
👍

**Comment by addityasingh** [comment]
@cschockaert There are some issues with `prettier` formating which can be fixed by running `yarn fix`. Can you please run that push the changes again?

**Comment by vigneshshanmugam** [comment]
👍

**Comment by addityasingh** [comment]
👍

**Comment by vigneshshanmugam** [comment]
👍

**Pull request merged**
